# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pctl < Formula
  desc "Command Line Interface tool for Paralus"
  homepage "https://github.com/paralus/cli"
  version "0.0.1"
  license "Apache License 2.0"

  on_macos do
    url "https://github.com/rustiever/cli/releases/download/v0.0.1/pctl_0.0.1_darwin_all.tar.gz"
    sha256 "5494e011446a7ea61432cd0879dd3a67d0757528bfb9b48e687818e840b15f1e"

    def install
      bin.install "pctl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rustiever/cli/releases/download/v0.0.1/pctl_0.0.1_linux_amd64.tar.gz"
      sha256 "ccafe3ac8c469491e73ec7ed684c78ba53491a707d02b2af524aac1731a2a8a6"

      def install
        bin.install "pctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rustiever/cli/releases/download/v0.0.1/pctl_0.0.1_linux_arm64.tar.gz"
      sha256 "e21c6537bcb5f5e02c5ad7c751ccb06b162998f0cc6293abce20dcbd2f8fa9ef"

      def install
        bin.install "pctl"
      end
    end
  end
end
