# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pctl < Formula
  desc "Command Line Interface tool for Paralus"
  homepage "https://github.com/paralus/cli"
  version "0.0.3"
  license "Apache License 2.0"

  on_macos do
    url "https://github.com/rustiever/cli/releases/download/v0.0.3/pctl_0.0.3_darwin_all.tar.gz"
    sha256 "c37f5d50b67f5a7c8195e00e14033b7d300e6d65eeee8b11791aedc18fc8ac4d"

    def install
      bin.install "pctl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rustiever/cli/releases/download/v0.0.3/pctl_0.0.3_linux_amd64.tar.gz"
      sha256 "9a241861b9bde076baccf613b8e98268826e9a1ef45ef5fc4c42db899568107f"

      def install
        bin.install "pctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rustiever/cli/releases/download/v0.0.3/pctl_0.0.3_linux_arm64.tar.gz"
      sha256 "5fded7b14e9f12c825a16e0de1b76e8e0dd5e904f5e94763e53523b5c02e5630"

      def install
        bin.install "pctl"
      end
    end
  end
end
