# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pctl < Formula
  desc "Command Line Interface tool for Paralus"
  homepage "https://github.com/paralus/cli"
  version "0.0.3"
  license "Apache License 2.0"

  on_macos do
    url "https://github.com/rustiever/cli/releases/download/v0.0.3/pctl_0.0.3_darwin_all.tar.gz"
    sha256 "f1b3b5225cc67a9f6a96b71cceb172e66b64ef09104a870306e63e86832499d0"

    def install
      bin.install "pctl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rustiever/cli/releases/download/v0.0.3/pctl_0.0.3_linux_amd64.tar.gz"
      sha256 "a757b393495ed96532a6b9e989d40b71b219419fb52bdbc188b6c81d13385bbe"

      def install
        bin.install "pctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rustiever/cli/releases/download/v0.0.3/pctl_0.0.3_linux_arm64.tar.gz"
      sha256 "5025a54b612b5dea704c50d2d97fdbf8451f2e13fe722e5893de17d275d47455"

      def install
        bin.install "pctl"
      end
    end
  end
end
